### ISSUE TITLE
Image.getSize for webp 

### ISSUE THREAD

**Issue by younes200** [TGPSKI/react-native-webp-support#2]
Hi,
Thank you for this webp support, it's very helpful ! 
I'm using a custom Image component which basically uses [Image.getSize](https://facebook.github.io/react-native/docs/image.html#getsize) to keep the size ratio. But it looks like **Image.getSize** always returns 0 (I only tried this with local files aka **file://** not remote)

Digging into react native source code [here](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageViewManager.m#L52) shows that the **RCTImageLoader**  rely on **RCTImageDataDecoder** to retrive the image dimensions.

Any idea what can cause this issue ?
Thank you.

**Comment by binlaniua** [comment]
i have the same problem..

**Comment by BunHouth** [comment]
I have the same problem. Anyone solve this issue yet?

**Comment by danghung24031992** [comment]
I same

**Comment by vikasg603** [comment]
Hey, @younes200 have you got any solution for this issue?
